# Generated by Django 4.1.7 on 2023-04-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='priece',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
