# Generated by Django 4.1.7 on 2023-04-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_priece'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='priece',
            new_name='price',
        ),
    ]
